name: Run Jaffle Shop Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "dlt[duckdb]" requests

      - name: Run pipeline
        run: |
          python main.py